name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - ipykernel=6.15.1
  - ipywidgets=7.7.1
  - pandas-profiling=3.2.0
  - pyarrow=2.0
  - pip:
      - protobuf==3.20.*
      - wandb==0.10.31
